config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :bigint           not null, primary key
#  birthday     :date
#  gender       :integer
#  introduction :text
#  nickname     :string
#  subscribed   :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
  enum gender: { male: 0, female: 1, other: 2 }
  belongs_to :user
  has_one_attached :avatar

  def age
    return '不明' unless birthday.present?
    years = Time.zone.now.year - birthday.year
    days = Time.zone.now.yday - birthday.yday

    if days < 0
      "#{years - 1}歳"
    else
      "#{years}歳"
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: 'プロフィールを更新しました'
    else
      flash.now[:error] = 'プロフィールを更新できませんでした'
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :gender,
      :birthday,
      :subscribed,
      :avatar
    )
  end
end

app/views/profiles/edit.html.haml
.container
  %h2.page-title
    Edit Profile
  %ul.errorMessages
    - @profile.errors.full_messages.each do |message|
      %li= message
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    .field
      = f.label :avatar
    %div
      = f.file_field :avatar, class: 'file'
    .field
      = f.label :nickname
    %div
      = f.text_field :nickname, class: 'text'
    .field
      = f.label :introduction
    %div
      = f.text_area :introduction
    .field
      = f.label :gender
    %div
      = f.select :gender, Profile.genders.map{ |k, v| [ I18n.t("enum.genders.#{k}"), k ] }, {}, {class: 'text'}
    .field
      = f.label :birthday
    %div
      = f.date_field :birthday, class: 'text'
    .check
      = f.check_box :subscribed
      = f.label :subscribed, class: 'check-font'
    = f.submit 'Submit', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profile
    .profilePage_user
      .profilePage_user_image
        = image_tag current_user.avatar_image
      .profilePage_user_basicInfo
        .profilePage_user_name
          .profilePage_user_displayName
            = "#{current_user.display_name} (#{current_user.age}・#{I18n.t("enum.genders.#{current_user.gender}")})"
          .profilePage_user_actionButton
            = link_to 'Edit', edit_profile_path
    .profilePage_user_introduction
      = current_user.profile&.introduction
  - current_user.boards.each do |board|
    = render 'commons/board', board: board