config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  deadline    :date
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
class Task < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :user
  belongs_to :board
  has_many :comments, dependent: :destroy

  has_one_attached :eyecatch
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_board, only: [:new, :create]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def show
    board = Board.find(params[:board_id])
    @task = board.tasks.find(params[:id])
    @comments = @task.comments
  end

  def new
    @task = @board.tasks.build
    @task.user = current_user
  end

  def create
    @task = @board.tasks.build(task_params)
    @task.user = current_user
    if @task.save
      redirect_to board_path(@board), notice: 'タスクを投稿しました'
    else
      flash.now[:error] = 'タスクの投稿に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    @task = current_user.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to board_task_path(@task.board, @task), notice: 'タスクを更新しました'
    else
      flash.now[:error] = 'タスクの更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    task = current_user.tasks.find(params[:id])
    task.destroy!
    redirect_to board_path(task.board), status: :see_other, notice: 'タスクを削除しました'
  end

  private
  def task_params
    params.require(:task).permit(:name, :description, :deadline, :eyecatch)
  end

  def set_board
    @board = Board.find(params[:board_id])
  end

end

app/views/tasks/_form.html.haml
.container
  %h2.page-title
    = pageTitle
  %ul.errorMessages
    - task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: task, url: url, local: true) do |f|
    .field
      = f.label :deadline
    %div
      = f.date_field :deadline, class: 'deadline'
    .field
      = f.label :eyecatch
    %div
      = f.file_field :eyecatch, class: 'file'
    - if task.eyecatch.attached?
      .file_message
        現在のアイキャッチ画像は変更されません。
        %br>/
        変更する場合は新しいファイルを選択してください。
    .field
      = f.label :name
    %div
      = f.text_field :name, class: 'text'
    .field
      = f.label :description
    %div
      = f.text_area :description
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/edit.html.haml
= render 'form', task: @task, url: board_task_path(@task.board, @task), pageTitle: 'Edit Task'

app/views/tasks/new.html.haml
= render 'form', task: @task, url: board_tasks_path(@board), pageTitle: 'New Task'

app/views/tasks/show.html.haml
.container
  / タスク詳細
  .task-details
    .page-header
      %h2.page-title= @task.name
      - if user_signed_in? && current_user.has_written_task?(@task)
        .detail_actions
          .dropdown
            = image_tag 'combined-shape.png', class: "dropdown-button"
            .dropdown-content
              = image_tag 'card1.png', class: "dropdown-content-bg"
              .dropdown-content-link-menu
                = link_to 'Edit', edit_board_task_path(@task.board, @task), class: "dropdown-content-link"
                = link_to 'Delete', board_task_path(@task.board, @task), data: { turbo_method: 'delete', turbo_confirm: '削除してもよろしいですか？' }, class: "dropdown-content-link"
    - if @task.eyecatch.attached?
      .task-details_image
        = image_tag @task.eyecatch
    .task-details_description
      = @task.description
  / コメント一覧
  .comment_container
    %h3.comment_header Comment
    .comments
      - @comments.each do |comment|
        .comment
          .comment_icon
            = image_tag comment.user.avatar_image, class: "comment_icon-image"
          .comment_content
            = comment.content
  / コメント追加ボタン
  = link_to new_board_task_comment_path(@task.board, @task) do
    .add-new-comment
      %p.add-new-comment_text + Add new comment