config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/views/commons/_board.html.haml
.board
  .board_flex-items
    .board_content
      = link_to board_path(board) do
        .board_name
          = board.name
        .board_description
          = board.description
        .board_editor
          = image_tag board.user.avatar_image, class: "board_editor-icon"
    - if user_signed_in? && current_user.has_written_board?(board)
      .detail_actions
        .dropdown
          = image_tag 'combined-shape.png', class: "dropdown-button"
          .dropdown-content
            = image_tag 'card1.png', class: "dropdown-content-bg"
            .dropdown-content-link-menu
              = link_to 'Edit', edit_board_path(board), class: "dropdown-content-link"
              = link_to 'Delete', board_path(board), data: { turbo_method: 'delete', turbo_confirm: '削除してもよろしいですか？' }, class: "dropdown-content-link"