config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'boards#index'

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text             not null
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
class Board < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def show
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to root_path, notice: 'ボードを投稿しました'
    else
      flash.now[:error] = 'ボードの投稿に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to root_path, notice: 'ボードを更新しました'
    else
      flash.now[:error] = 'ボードの更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, status: :see_other, notice: 'ボードを削除しました'
  end

  private
  def board_params
    params.require(:board).permit(:name, :description)
  end

  def set_board
    @board = Board.find(params[:id])
  end
end

app/views/boards/_form.html.haml
.container
  %h2.page-title
    = pageTitle
  %ul.errorMessages
    - board.errors.full_messages.each do |message|
      %li= message
  = form_with(model: board, local: true) do |f|
    .field
      = f.label :name
    %div
      = f.text_field :name, class: 'text'
    .field
      = f.label :description
    %div
      = f.text_area :description
    = f.submit 'Submit', class: 'btn-primary'

app/views/boards/_task.html.haml
.task
  .task_content
    = link_to board_task_path(task.board, task) do
      - if task.eyecatch.attached?
        .task_image
          = image_tag task.eyecatch
      .task_name
        = task.name
      .task_description
        = task.description
      .task_bottom
        .task_editor
          = image_tag task.user.avatar_image, class: "task_editor-icon"
        .task_comment
          .task_comment-count
            = task.comments.count
          .task_comment-icon
            = image_tag 'message-square-outline.png', class: "task_comment-icon-img"
      - if task.deadline?
        .task_deadline
          Deadline：#{l task.deadline}

app/views/boards/edit.html.haml
= render 'form', board: @board, pageTitle: 'Edit Board'

app/views/boards/index.html.haml
.container
  %h2.page-title All Boards
  .boards
    - @boards.each do |board|
      = render 'commons/board', board: board
    = link_to new_board_path do
      .add-new-board
        %p.add-new-board_text + Add new board

app/views/boards/new.html.haml
= render 'form', board: @board, pageTitle: 'New Board'

app/views/boards/show.html.haml
.container
  %h2.page-title= @board.name
  .tasks
    - @tasks.each do |task|
      = render 'task', task: task
    = link_to new_board_task_path(@board) do
      .add-new-task
        %p.add-new-task_text + Add new card